name: sojo_link
description: "A Flutter plugin for handling dynamic links with SojoLink"
version: 0.0.1
homepage: https://sojolink.com/
repository: https://github.com/truenary/sojolink_pkg

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.truenary.sojo_link
        pluginClass: SojoLinkPlugin
      ios:
        pluginClass: SojoLinkPlugin
