name: Release Workflow
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: 'Specify release type: regular, alpha, beta, or rc'
        required: true
        default: 'regular'
        type: choice
        options:
          - regular
          - alpha
          - beta
          - rc
jobs:
  release:
    runs-on: ubuntu-latest

    # Use the protected environment
    environment: Release

    # Grant permissions required to push commits/tags
    permissions:
      contents: write
      actions: write

    # Set environment variables
    env:
      RELEASE_TYPE: ${{ github.event.inputs.release-type }}
      GIT_USER_NAME: ${{ vars.GIT_USER_NAME }}
      GIT_USER_EMAIL: ${{ vars.GIT_USER_EMAIL }}

    steps:
      # Step 1: Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN_GITHUB }}

      # Install Node.js dependencies
      - name: Install Node dependencies
        run: npm ci

      # Set Git user configuration (for tagging and committing)
      - name: Configure Git user
        run: |
          git config --global user.email "$GIT_USER_EMAIL"
          git config --global user.name "$GIT_USER_NAME"

      # Run release-it to publish version based on input type
      - name: Run release-it
        run: |
          if [ "$RELEASE_TYPE" == "regular" ]; then
            npx release-it --ci  # Regular release
          else
            npx release-it --ci --preRelease="$RELEASE_TYPE"  # Pre-release (alpha, beta, rc)
          fi
        env:
          # Passes the GitHub token to release-it
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}