name: Publish Workflow
on:
  push:
    tags:
      - 'v*'  # Only react to version tags
jobs:
  publish:
    # Grants permissions for the job
    permissions:
      id-token: write  # Required for authentication using OIDC
      contents: read    # Required for checking out code

    # Uses the Dart setup workflow for publishing
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1